package(default_visibility = ["//visibility:public"])

cc_binary(
  name = "argparse-example",
  srcs = ["argparse_example.cc"],
  deps = ["//argue"],
)

cc_binary(
  name = "simple-example",
  srcs = ["simple_example.cc"],
  deps = ["//argue"],
)

cc_binary(
  name = "subparser-example",
  srcs = ["subparser_example.cc"],
  deps = ["//argue"],
)
