// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tangent/protostruct/test/test_messages.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "tangent/protostruct/test/test_messages.pb.h"

#include <algorithm>

#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/wire_format.h>
#include <google/protobuf/wire_format_lite_inl.h>
// @@protoc_insertion_point(includes)

namespace tangent {
namespace test {

namespace {

const ::google::protobuf::Descriptor* MyMessageA_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
    MyMessageA_reflection_ = NULL;
const ::google::protobuf::Descriptor* MyMessageB_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
    MyMessageB_reflection_ = NULL;
const ::google::protobuf::Descriptor* MyMessageC_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
    MyMessageC_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* MyEnumA_descriptor_ = NULL;

}  // namespace

void protobuf_AssignDesc_tangent_2fprotostruct_2ftest_2ftest_5fmessages_2eproto()
    GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_tangent_2fprotostruct_2ftest_2ftest_5fmessages_2eproto() {
  protobuf_AddDesc_tangent_2fprotostruct_2ftest_2ftest_5fmessages_2eproto();
  const ::google::protobuf::FileDescriptor* file =
      ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
          "tangent/protostruct/test/test_messages.proto");
  GOOGLE_CHECK(file != NULL);
  MyMessageA_descriptor_ = file->message_type(0);
  static const int MyMessageA_offsets_[4] = {
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MyMessageA, fielda_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MyMessageA, fieldb_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MyMessageA, fieldc_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MyMessageA, fieldd_),
  };
  MyMessageA_reflection_ = ::google::protobuf::internal::
      GeneratedMessageReflection::NewGeneratedMessageReflection(
          MyMessageA_descriptor_, MyMessageA::default_instance_,
          MyMessageA_offsets_, -1, -1, -1, sizeof(MyMessageA),
          GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MyMessageA,
                                                         _internal_metadata_),
          GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(
              MyMessageA, _is_default_instance_));
  MyMessageB_descriptor_ = file->message_type(1);
  static const int MyMessageB_offsets_[1] = {
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MyMessageB, fielda_),
  };
  MyMessageB_reflection_ = ::google::protobuf::internal::
      GeneratedMessageReflection::NewGeneratedMessageReflection(
          MyMessageB_descriptor_, MyMessageB::default_instance_,
          MyMessageB_offsets_, -1, -1, -1, sizeof(MyMessageB),
          GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MyMessageB,
                                                         _internal_metadata_),
          GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(
              MyMessageB, _is_default_instance_));
  MyMessageC_descriptor_ = file->message_type(2);
  static const int MyMessageC_offsets_[2] = {
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MyMessageC, fielda_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MyMessageC, fieldb_),
  };
  MyMessageC_reflection_ = ::google::protobuf::internal::
      GeneratedMessageReflection::NewGeneratedMessageReflection(
          MyMessageC_descriptor_, MyMessageC::default_instance_,
          MyMessageC_offsets_, -1, -1, -1, sizeof(MyMessageC),
          GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MyMessageC,
                                                         _internal_metadata_),
          GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(
              MyMessageC, _is_default_instance_));
  MyEnumA_descriptor_ = file->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(
      &protobuf_AssignDescriptors_once_,
      &protobuf_AssignDesc_tangent_2fprotostruct_2ftest_2ftest_5fmessages_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      MyMessageA_descriptor_, &MyMessageA::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      MyMessageB_descriptor_, &MyMessageB::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      MyMessageC_descriptor_, &MyMessageC::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_tangent_2fprotostruct_2ftest_2ftest_5fmessages_2eproto() {
  delete MyMessageA::default_instance_;
  delete MyMessageA_reflection_;
  delete MyMessageB::default_instance_;
  delete MyMessageB_reflection_;
  delete MyMessageC::default_instance_;
  delete MyMessageC_reflection_;
}

void protobuf_AddDesc_tangent_2fprotostruct_2ftest_2ftest_5fmessages_2eproto()
    GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_tangent_2fprotostruct_2ftest_2ftest_5fmessages_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      "\n,tangent/protostruct/test/test_messages"
      ".proto\022\014tangent.test\"c\n\nMyMessageA\022\016\n\006fi"
      "eldA\030\001 \001(\021\022\016\n\006fieldB\030\002 "
      "\001(\001\022\016\n\006fieldC\030\003 \001"
      "(\004\022%\n\006fieldD\030\004 \001(\0162\025.tangent.test.MyEnum"
      "A\"Z\n\nMyMessageB\022(\n\006fieldA\030\002 \001(\0132\030.tangen"
      "t.test."
      "MyMessageAJ\004\010\001\020\002J\004\010\003\020\004J\004\010\010\020\tJ"
      "\004\010\014\020"
      "\016J\004\010\004\020\005J\004\010\007\020\010\"J\n\nMyMessageC\022("
      "\n\006fieldA\030\001 "
      "\003(\0132\030.tangent.test.MyMessageA\022\022\n\006fieldB\030"
      "\002 "
      "\003(\005B\002\020\001*E\n\007MyEnumA\022\022\n\016MyEnumA_"
      "VALUE1\020\000"
      "\022\022\n\016MyEnumA_VALUE2\020\001\022\022\n\016MyEnumA_VALUE3\020\002"
      "b\006proto3",
      408);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
      "tangent/protostruct/test/test_messages.proto", &protobuf_RegisterTypes);
  MyMessageA::default_instance_ = new MyMessageA();
  MyMessageB::default_instance_ = new MyMessageB();
  MyMessageC::default_instance_ = new MyMessageC();
  MyMessageA::default_instance_->InitAsDefaultInstance();
  MyMessageB::default_instance_->InitAsDefaultInstance();
  MyMessageC::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(
      &protobuf_ShutdownFile_tangent_2fprotostruct_2ftest_2ftest_5fmessages_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct
    StaticDescriptorInitializer_tangent_2fprotostruct_2ftest_2ftest_5fmessages_2eproto {
  StaticDescriptorInitializer_tangent_2fprotostruct_2ftest_2ftest_5fmessages_2eproto() {
    protobuf_AddDesc_tangent_2fprotostruct_2ftest_2ftest_5fmessages_2eproto();
  }
} static_descriptor_initializer_tangent_2fprotostruct_2ftest_2ftest_5fmessages_2eproto_;
const ::google::protobuf::EnumDescriptor* MyEnumA_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MyEnumA_descriptor_;
}
bool MyEnumA_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int MyMessageA::kFieldAFieldNumber;
const int MyMessageA::kFieldBFieldNumber;
const int MyMessageA::kFieldCFieldNumber;
const int MyMessageA::kFieldDFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

MyMessageA::MyMessageA()
    : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:tangent.test.MyMessageA)
}

void MyMessageA::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

MyMessageA::MyMessageA(const MyMessageA& from)
    : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:tangent.test.MyMessageA)
}

void MyMessageA::SharedCtor() {
  _is_default_instance_ = false;
  _cached_size_ = 0;
  fielda_ = 0;
  fieldb_ = 0;
  fieldc_ = GOOGLE_ULONGLONG(0);
  fieldd_ = 0;
}

MyMessageA::~MyMessageA() {
  // @@protoc_insertion_point(destructor:tangent.test.MyMessageA)
  SharedDtor();
}

void MyMessageA::SharedDtor() {
  if (this != default_instance_) {
  }
}

void MyMessageA::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MyMessageA::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MyMessageA_descriptor_;
}

const MyMessageA& MyMessageA::default_instance() {
  if (default_instance_ == NULL)
    protobuf_AddDesc_tangent_2fprotostruct_2ftest_2ftest_5fmessages_2eproto();
  return *default_instance_;
}

MyMessageA* MyMessageA::default_instance_ = NULL;

MyMessageA* MyMessageA::New(::google::protobuf::Arena* arena) const {
  MyMessageA* n = new MyMessageA;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void MyMessageA::Clear() {
// @@protoc_insertion_point(message_clear_start:tangent.test.MyMessageA)
#if defined(__clang__)
#define ZR_HELPER_(f)                                                 \
  _Pragma("clang diagnostic push")                                    \
      _Pragma(                                                        \
          "clang diagnostic ignored "                                 \
          "\"-Winvalid-offsetof\"") __builtin_offsetof(MyMessageA, f) \
          _Pragma("clang diagnostic pop")
#else
#define ZR_HELPER_(f) \
  reinterpret_cast<char*>(&reinterpret_cast<MyMessageA*>(16)->f)
#endif

#define ZR_(first, last)                                                      \
  do {                                                                        \
    ::memset(&first, 0, ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last)); \
  } while (0)

  ZR_(fieldb_, fieldc_);

#undef ZR_HELPER_
#undef ZR_
}

bool MyMessageA::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) \
  if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:tangent.test.MyMessageA)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p =
        input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (
        ::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional sint32 fieldA = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
               ::google::protobuf::int32,
               ::google::protobuf::internal::WireFormatLite::TYPE_SINT32>(
              input, &fielda_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(17)) goto parse_fieldB;
        break;
      }

      // optional double fieldB = 2;
      case 2: {
        if (tag == 17) {
        parse_fieldB:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
               double,
               ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
              input, &fieldb_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_fieldC;
        break;
      }

      // optional uint64 fieldC = 3;
      case 3: {
        if (tag == 24) {
        parse_fieldC:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
               ::google::protobuf::uint64,
               ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
              input, &fieldc_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(32)) goto parse_fieldD;
        break;
      }

      // optional .tangent.test.MyEnumA fieldD = 4;
      case 4: {
        if (tag == 32) {
        parse_fieldD:
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
               int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
              input, &value)));
          set_fieldd(static_cast< ::tangent::test::MyEnumA>(value));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
                ::google::protobuf::internal::WireFormatLite::
                    WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input,
                                                                    tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:tangent.test.MyMessageA)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:tangent.test.MyMessageA)
  return false;
#undef DO_
}

void MyMessageA::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:tangent.test.MyMessageA)
  // optional sint32 fieldA = 1;
  if (this->fielda() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteSInt32(1, this->fielda(),
                                                              output);
  }

  // optional double fieldB = 2;
  if (this->fieldb() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(2, this->fieldb(),
                                                              output);
  }

  // optional uint64 fieldC = 3;
  if (this->fieldc() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(3, this->fieldc(),
                                                              output);
  }

  // optional .tangent.test.MyEnumA fieldD = 4;
  if (this->fieldd() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(4, this->fieldd(),
                                                            output);
  }

  // @@protoc_insertion_point(serialize_end:tangent.test.MyMessageA)
}

::google::protobuf::uint8* MyMessageA::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:tangent.test.MyMessageA)
  // optional sint32 fieldA = 1;
  if (this->fielda() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteSInt32ToArray(
        1, this->fielda(), target);
  }

  // optional double fieldB = 2;
  if (this->fieldb() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(
        2, this->fieldb(), target);
  }

  // optional uint64 fieldC = 3;
  if (this->fieldc() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(
        3, this->fieldc(), target);
  }

  // optional .tangent.test.MyEnumA fieldD = 4;
  if (this->fieldd() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
        4, this->fieldd(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:tangent.test.MyMessageA)
  return target;
}

int MyMessageA::ByteSize() const {
  // @@protoc_insertion_point(message_byte_size_start:tangent.test.MyMessageA)
  int total_size = 0;

  // optional sint32 fieldA = 1;
  if (this->fielda() != 0) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::SInt32Size(
                          this->fielda());
  }

  // optional double fieldB = 2;
  if (this->fieldb() != 0) {
    total_size += 1 + 8;
  }

  // optional uint64 fieldC = 3;
  if (this->fieldc() != 0) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::UInt64Size(
                          this->fieldc());
  }

  // optional .tangent.test.MyEnumA fieldD = 4;
  if (this->fieldd() != 0) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::EnumSize(
                          this->fieldd());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MyMessageA::MergeFrom(const ::google::protobuf::Message& from) {
  // @@protoc_insertion_point(generalized_merge_from_start:tangent.test.MyMessageA)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const MyMessageA* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const MyMessageA>(
          &from);
  if (source == NULL) {
    // @@protoc_insertion_point(generalized_merge_from_cast_fail:tangent.test.MyMessageA)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    // @@protoc_insertion_point(generalized_merge_from_cast_success:tangent.test.MyMessageA)
    MergeFrom(*source);
  }
}

void MyMessageA::MergeFrom(const MyMessageA& from) {
  // @@protoc_insertion_point(class_specific_merge_from_start:tangent.test.MyMessageA)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.fielda() != 0) {
    set_fielda(from.fielda());
  }
  if (from.fieldb() != 0) {
    set_fieldb(from.fieldb());
  }
  if (from.fieldc() != 0) {
    set_fieldc(from.fieldc());
  }
  if (from.fieldd() != 0) {
    set_fieldd(from.fieldd());
  }
}

void MyMessageA::CopyFrom(const ::google::protobuf::Message& from) {
  // @@protoc_insertion_point(generalized_copy_from_start:tangent.test.MyMessageA)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MyMessageA::CopyFrom(const MyMessageA& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:tangent.test.MyMessageA)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MyMessageA::IsInitialized() const {
  return true;
}

void MyMessageA::Swap(MyMessageA* other) {
  if (other == this) return;
  InternalSwap(other);
}
void MyMessageA::InternalSwap(MyMessageA* other) {
  std::swap(fielda_, other->fielda_);
  std::swap(fieldb_, other->fieldb_);
  std::swap(fieldc_, other->fieldc_);
  std::swap(fieldd_, other->fieldd_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata MyMessageA::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MyMessageA_descriptor_;
  metadata.reflection = MyMessageA_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// MyMessageA

// optional sint32 fieldA = 1;
void MyMessageA::clear_fielda() {
  fielda_ = 0;
}
::google::protobuf::int32 MyMessageA::fielda() const {
  // @@protoc_insertion_point(field_get:tangent.test.MyMessageA.fieldA)
  return fielda_;
}
void MyMessageA::set_fielda(::google::protobuf::int32 value) {
  fielda_ = value;
  // @@protoc_insertion_point(field_set:tangent.test.MyMessageA.fieldA)
}

// optional double fieldB = 2;
void MyMessageA::clear_fieldb() {
  fieldb_ = 0;
}
double MyMessageA::fieldb() const {
  // @@protoc_insertion_point(field_get:tangent.test.MyMessageA.fieldB)
  return fieldb_;
}
void MyMessageA::set_fieldb(double value) {
  fieldb_ = value;
  // @@protoc_insertion_point(field_set:tangent.test.MyMessageA.fieldB)
}

// optional uint64 fieldC = 3;
void MyMessageA::clear_fieldc() {
  fieldc_ = GOOGLE_ULONGLONG(0);
}
::google::protobuf::uint64 MyMessageA::fieldc() const {
  // @@protoc_insertion_point(field_get:tangent.test.MyMessageA.fieldC)
  return fieldc_;
}
void MyMessageA::set_fieldc(::google::protobuf::uint64 value) {
  fieldc_ = value;
  // @@protoc_insertion_point(field_set:tangent.test.MyMessageA.fieldC)
}

// optional .tangent.test.MyEnumA fieldD = 4;
void MyMessageA::clear_fieldd() {
  fieldd_ = 0;
}
::tangent::test::MyEnumA MyMessageA::fieldd() const {
  // @@protoc_insertion_point(field_get:tangent.test.MyMessageA.fieldD)
  return static_cast< ::tangent::test::MyEnumA>(fieldd_);
}
void MyMessageA::set_fieldd(::tangent::test::MyEnumA value) {
  fieldd_ = value;
  // @@protoc_insertion_point(field_set:tangent.test.MyMessageA.fieldD)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int MyMessageB::kFieldAFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

MyMessageB::MyMessageB()
    : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:tangent.test.MyMessageB)
}

void MyMessageB::InitAsDefaultInstance() {
  _is_default_instance_ = true;
  fielda_ = const_cast< ::tangent::test::MyMessageA*>(
      &::tangent::test::MyMessageA::default_instance());
}

MyMessageB::MyMessageB(const MyMessageB& from)
    : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:tangent.test.MyMessageB)
}

void MyMessageB::SharedCtor() {
  _is_default_instance_ = false;
  _cached_size_ = 0;
  fielda_ = NULL;
}

MyMessageB::~MyMessageB() {
  // @@protoc_insertion_point(destructor:tangent.test.MyMessageB)
  SharedDtor();
}

void MyMessageB::SharedDtor() {
  if (this != default_instance_) {
    delete fielda_;
  }
}

void MyMessageB::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MyMessageB::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MyMessageB_descriptor_;
}

const MyMessageB& MyMessageB::default_instance() {
  if (default_instance_ == NULL)
    protobuf_AddDesc_tangent_2fprotostruct_2ftest_2ftest_5fmessages_2eproto();
  return *default_instance_;
}

MyMessageB* MyMessageB::default_instance_ = NULL;

MyMessageB* MyMessageB::New(::google::protobuf::Arena* arena) const {
  MyMessageB* n = new MyMessageB;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void MyMessageB::Clear() {
  // @@protoc_insertion_point(message_clear_start:tangent.test.MyMessageB)
  if (GetArenaNoVirtual() == NULL && fielda_ != NULL) delete fielda_;
  fielda_ = NULL;
}

bool MyMessageB::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) \
  if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:tangent.test.MyMessageB)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p =
        input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (
        ::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .tangent.test.MyMessageA fieldA = 2;
      case 2: {
        if (tag == 18) {
          DO_(::google::protobuf::internal::WireFormatLite::
                  ReadMessageNoVirtual(input, mutable_fielda()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
                ::google::protobuf::internal::WireFormatLite::
                    WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input,
                                                                    tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:tangent.test.MyMessageB)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:tangent.test.MyMessageB)
  return false;
#undef DO_
}

void MyMessageB::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:tangent.test.MyMessageB)
  // optional .tangent.test.MyMessageA fieldA = 2;
  if (this->has_fielda()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
        2, *this->fielda_, output);
  }

  // @@protoc_insertion_point(serialize_end:tangent.test.MyMessageB)
}

::google::protobuf::uint8* MyMessageB::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:tangent.test.MyMessageB)
  // optional .tangent.test.MyMessageA fieldA = 2;
  if (this->has_fielda()) {
    target = ::google::protobuf::internal::WireFormatLite::
        InternalWriteMessageNoVirtualToArray(2, *this->fielda_, false, target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:tangent.test.MyMessageB)
  return target;
}

int MyMessageB::ByteSize() const {
  // @@protoc_insertion_point(message_byte_size_start:tangent.test.MyMessageB)
  int total_size = 0;

  // optional .tangent.test.MyMessageA fieldA = 2;
  if (this->has_fielda()) {
    total_size +=
        1 + ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
                *this->fielda_);
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MyMessageB::MergeFrom(const ::google::protobuf::Message& from) {
  // @@protoc_insertion_point(generalized_merge_from_start:tangent.test.MyMessageB)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const MyMessageB* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const MyMessageB>(
          &from);
  if (source == NULL) {
    // @@protoc_insertion_point(generalized_merge_from_cast_fail:tangent.test.MyMessageB)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    // @@protoc_insertion_point(generalized_merge_from_cast_success:tangent.test.MyMessageB)
    MergeFrom(*source);
  }
}

void MyMessageB::MergeFrom(const MyMessageB& from) {
  // @@protoc_insertion_point(class_specific_merge_from_start:tangent.test.MyMessageB)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.has_fielda()) {
    mutable_fielda()->::tangent::test::MyMessageA::MergeFrom(from.fielda());
  }
}

void MyMessageB::CopyFrom(const ::google::protobuf::Message& from) {
  // @@protoc_insertion_point(generalized_copy_from_start:tangent.test.MyMessageB)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MyMessageB::CopyFrom(const MyMessageB& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:tangent.test.MyMessageB)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MyMessageB::IsInitialized() const {
  return true;
}

void MyMessageB::Swap(MyMessageB* other) {
  if (other == this) return;
  InternalSwap(other);
}
void MyMessageB::InternalSwap(MyMessageB* other) {
  std::swap(fielda_, other->fielda_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata MyMessageB::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MyMessageB_descriptor_;
  metadata.reflection = MyMessageB_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// MyMessageB

// optional .tangent.test.MyMessageA fieldA = 2;
bool MyMessageB::has_fielda() const {
  return !_is_default_instance_ && fielda_ != NULL;
}
void MyMessageB::clear_fielda() {
  if (GetArenaNoVirtual() == NULL && fielda_ != NULL) delete fielda_;
  fielda_ = NULL;
}
const ::tangent::test::MyMessageA& MyMessageB::fielda() const {
  // @@protoc_insertion_point(field_get:tangent.test.MyMessageB.fieldA)
  return fielda_ != NULL ? *fielda_ : *default_instance_->fielda_;
}
::tangent::test::MyMessageA* MyMessageB::mutable_fielda() {
  if (fielda_ == NULL) {
    fielda_ = new ::tangent::test::MyMessageA;
  }
  // @@protoc_insertion_point(field_mutable:tangent.test.MyMessageB.fieldA)
  return fielda_;
}
::tangent::test::MyMessageA* MyMessageB::release_fielda() {
  // @@protoc_insertion_point(field_release:tangent.test.MyMessageB.fieldA)

  ::tangent::test::MyMessageA* temp = fielda_;
  fielda_ = NULL;
  return temp;
}
void MyMessageB::set_allocated_fielda(::tangent::test::MyMessageA* fielda) {
  delete fielda_;
  fielda_ = fielda;
  if (fielda) {
  } else {
  }
  // @@protoc_insertion_point(field_set_allocated:tangent.test.MyMessageB.fieldA)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int MyMessageC::kFieldAFieldNumber;
const int MyMessageC::kFieldBFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

MyMessageC::MyMessageC()
    : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:tangent.test.MyMessageC)
}

void MyMessageC::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

MyMessageC::MyMessageC(const MyMessageC& from)
    : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:tangent.test.MyMessageC)
}

void MyMessageC::SharedCtor() {
  _is_default_instance_ = false;
  _cached_size_ = 0;
}

MyMessageC::~MyMessageC() {
  // @@protoc_insertion_point(destructor:tangent.test.MyMessageC)
  SharedDtor();
}

void MyMessageC::SharedDtor() {
  if (this != default_instance_) {
  }
}

void MyMessageC::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MyMessageC::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MyMessageC_descriptor_;
}

const MyMessageC& MyMessageC::default_instance() {
  if (default_instance_ == NULL)
    protobuf_AddDesc_tangent_2fprotostruct_2ftest_2ftest_5fmessages_2eproto();
  return *default_instance_;
}

MyMessageC* MyMessageC::default_instance_ = NULL;

MyMessageC* MyMessageC::New(::google::protobuf::Arena* arena) const {
  MyMessageC* n = new MyMessageC;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void MyMessageC::Clear() {
  // @@protoc_insertion_point(message_clear_start:tangent.test.MyMessageC)
  fielda_.Clear();
  fieldb_.Clear();
}

bool MyMessageC::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) \
  if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:tangent.test.MyMessageC)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p =
        input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (
        ::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .tangent.test.MyMessageA fieldA = 1;
      case 1: {
        if (tag == 10) {
          DO_(input->IncrementRecursionDepth());
        parse_loop_fieldA:
          DO_(::google::protobuf::internal::WireFormatLite::
                  ReadMessageNoVirtualNoRecursionDepth(input, add_fielda()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(10)) goto parse_loop_fieldA;
        input->UnsafeDecrementRecursionDepth();
        if (input->ExpectTag(18)) goto parse_fieldB;
        break;
      }

      // repeated int32 fieldB = 2 [packed = true];
      case 2: {
        if (tag == 18) {
        parse_fieldB:
          DO_((
              ::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                  ::google::protobuf::int32,
                  ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                  input, this->mutable_fieldb())));
        } else if (tag == 16) {
          DO_((
              ::google::protobuf::internal::WireFormatLite::
                  ReadRepeatedPrimitiveNoInline<
                      ::google::protobuf::int32,
                      ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                      1, 18, input, this->mutable_fieldb())));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
                ::google::protobuf::internal::WireFormatLite::
                    WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input,
                                                                    tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:tangent.test.MyMessageC)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:tangent.test.MyMessageC)
  return false;
#undef DO_
}

void MyMessageC::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:tangent.test.MyMessageC)
  // repeated .tangent.test.MyMessageA fieldA = 1;
  for (unsigned int i = 0, n = this->fielda_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
        1, this->fielda(i), output);
  }

  // repeated int32 fieldB = 2 [packed = true];
  if (this->fieldb_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(
        2,
        ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
        output);
    output->WriteVarint32(_fieldb_cached_byte_size_);
  }
  for (int i = 0; i < this->fieldb_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32NoTag(
        this->fieldb(i), output);
  }

  // @@protoc_insertion_point(serialize_end:tangent.test.MyMessageC)
}

::google::protobuf::uint8* MyMessageC::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:tangent.test.MyMessageC)
  // repeated .tangent.test.MyMessageA fieldA = 1;
  for (unsigned int i = 0, n = this->fielda_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
        InternalWriteMessageNoVirtualToArray(1, this->fielda(i), false, target);
  }

  // repeated int32 fieldB = 2 [packed = true];
  if (this->fieldb_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
        2,
        ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
        target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
        _fieldb_cached_byte_size_, target);
  }
  for (int i = 0; i < this->fieldb_size(); i++) {
    target =
        ::google::protobuf::internal::WireFormatLite::WriteInt32NoTagToArray(
            this->fieldb(i), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:tangent.test.MyMessageC)
  return target;
}

int MyMessageC::ByteSize() const {
  // @@protoc_insertion_point(message_byte_size_start:tangent.test.MyMessageC)
  int total_size = 0;

  // repeated .tangent.test.MyMessageA fieldA = 1;
  total_size += 1 * this->fielda_size();
  for (int i = 0; i < this->fielda_size(); i++) {
    total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
            this->fielda(i));
  }

  // repeated int32 fieldB = 2 [packed = true];
  {
    int data_size = 0;
    for (int i = 0; i < this->fieldb_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->fieldb(i));
    }
    if (data_size > 0) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::Int32Size(
                            data_size);
    }
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _fieldb_cached_byte_size_ = data_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    total_size += data_size;
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MyMessageC::MergeFrom(const ::google::protobuf::Message& from) {
  // @@protoc_insertion_point(generalized_merge_from_start:tangent.test.MyMessageC)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const MyMessageC* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const MyMessageC>(
          &from);
  if (source == NULL) {
    // @@protoc_insertion_point(generalized_merge_from_cast_fail:tangent.test.MyMessageC)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    // @@protoc_insertion_point(generalized_merge_from_cast_success:tangent.test.MyMessageC)
    MergeFrom(*source);
  }
}

void MyMessageC::MergeFrom(const MyMessageC& from) {
  // @@protoc_insertion_point(class_specific_merge_from_start:tangent.test.MyMessageC)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  fielda_.MergeFrom(from.fielda_);
  fieldb_.MergeFrom(from.fieldb_);
}

void MyMessageC::CopyFrom(const ::google::protobuf::Message& from) {
  // @@protoc_insertion_point(generalized_copy_from_start:tangent.test.MyMessageC)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MyMessageC::CopyFrom(const MyMessageC& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:tangent.test.MyMessageC)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MyMessageC::IsInitialized() const {
  return true;
}

void MyMessageC::Swap(MyMessageC* other) {
  if (other == this) return;
  InternalSwap(other);
}
void MyMessageC::InternalSwap(MyMessageC* other) {
  fielda_.UnsafeArenaSwap(&other->fielda_);
  fieldb_.UnsafeArenaSwap(&other->fieldb_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata MyMessageC::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MyMessageC_descriptor_;
  metadata.reflection = MyMessageC_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// MyMessageC

// repeated .tangent.test.MyMessageA fieldA = 1;
int MyMessageC::fielda_size() const {
  return fielda_.size();
}
void MyMessageC::clear_fielda() {
  fielda_.Clear();
}
const ::tangent::test::MyMessageA& MyMessageC::fielda(int index) const {
  // @@protoc_insertion_point(field_get:tangent.test.MyMessageC.fieldA)
  return fielda_.Get(index);
}
::tangent::test::MyMessageA* MyMessageC::mutable_fielda(int index) {
  // @@protoc_insertion_point(field_mutable:tangent.test.MyMessageC.fieldA)
  return fielda_.Mutable(index);
}
::tangent::test::MyMessageA* MyMessageC::add_fielda() {
  // @@protoc_insertion_point(field_add:tangent.test.MyMessageC.fieldA)
  return fielda_.Add();
}
::google::protobuf::RepeatedPtrField< ::tangent::test::MyMessageA>*
MyMessageC::mutable_fielda() {
  // @@protoc_insertion_point(field_mutable_list:tangent.test.MyMessageC.fieldA)
  return &fielda_;
}
const ::google::protobuf::RepeatedPtrField< ::tangent::test::MyMessageA>&
MyMessageC::fielda() const {
  // @@protoc_insertion_point(field_list:tangent.test.MyMessageC.fieldA)
  return fielda_;
}

// repeated int32 fieldB = 2 [packed = true];
int MyMessageC::fieldb_size() const {
  return fieldb_.size();
}
void MyMessageC::clear_fieldb() {
  fieldb_.Clear();
}
::google::protobuf::int32 MyMessageC::fieldb(int index) const {
  // @@protoc_insertion_point(field_get:tangent.test.MyMessageC.fieldB)
  return fieldb_.Get(index);
}
void MyMessageC::set_fieldb(int index, ::google::protobuf::int32 value) {
  fieldb_.Set(index, value);
  // @@protoc_insertion_point(field_set:tangent.test.MyMessageC.fieldB)
}
void MyMessageC::add_fieldb(::google::protobuf::int32 value) {
  fieldb_.Add(value);
  // @@protoc_insertion_point(field_add:tangent.test.MyMessageC.fieldB)
}
const ::google::protobuf::RepeatedField< ::google::protobuf::int32>&
MyMessageC::fieldb() const {
  // @@protoc_insertion_point(field_list:tangent.test.MyMessageC.fieldB)
  return fieldb_;
}
::google::protobuf::RepeatedField< ::google::protobuf::int32>*
MyMessageC::mutable_fieldb() {
  // @@protoc_insertion_point(field_mutable_list:tangent.test.MyMessageC.fieldB)
  return &fieldb_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace test
}  // namespace tangent

// @@protoc_insertion_point(global_scope)
